import { PlanTable } from "lib/db/pg/schema.pg";

/** Default billing rows: single source for DB seed and auto-heal when `plan` is empty. */
export const DEFAULT_BILLING_PLAN_ROWS: (typeof PlanTable.$inferInsert)[] = [
  {
    code: "free",
    name: "免费版",
    monthlyPriceCents: 0,
    yearlyPriceCents: null,
    monthlyMsgLimit: 50,
    monthlyTokenLimit: 100_000,
    allowedModelPatterns: ["deepseek-v4-flash:free"],
    features: [
      "OpenRouter 统一路由；主力模型 deepseek/deepseek-v4-flash:free，响应快、推理扎实，综合体验明显优于豆包等国内免费档。",
      "每月 50 条消息",
      "10 万 token",
    ],
    displayOrder: 0,
    active: true,
  },
  {
    code: "standard",
    name: "标准版",
    monthlyPriceCents: 6800,
    yearlyPriceCents: 68_000,
    monthlyMsgLimit: 2000,
    monthlyTokenLimit: 5_000_000,
    allowedModelPatterns: ["deepseek-v4-flash:free", "deepseek-v4-pro"],
    features: [
      "OpenRouter；deepseek/deepseek-v4-pro，逻辑与代码能力全面跃升，长对话更稳，整体水准远超豆包。",
      "每月 2000 条消息",
      "500 万 token",
      "MCP 工具",
    ],
    displayOrder: 1,
    active: true,
  },
  {
    code: "enhanced",
    name: "加强版",
    monthlyPriceCents: 20_000,
    yearlyPriceCents: 200_000,
    monthlyMsgLimit: 5000,
    monthlyTokenLimit: 15_000_000,
    allowedModelPatterns: [
      "deepseek-v4-flash:free",
      "deepseek-v4-pro",
      "sonnet-4.6",
    ],
    features: [
      "OpenRouter；anthropic/claude-sonnet-4.6，复杂任务与长上下文表现突出，理解与创作质量远超豆包。",
      "每月 5000 条消息",
      "1500 万 token",
      "MCP 工具",
    ],
    displayOrder: 2,
    active: true,
  },
  {
    code: "pro",
    name: "专业版",
    monthlyPriceCents: 50_000,
    yearlyPriceCents: 500_000,
    monthlyMsgLimit: -1,
    monthlyTokenLimit: 50_000_000,
    allowedModelPatterns: ["*"],
    features: [
      "OpenRouter；anthropic/claude-opus-4.7，顶级推理与深度分析，面向高难度场景，能力层级远超豆包。",
      "无限消息",
      "5000 万 token",
      "工作流编排",
      "优先支持",
    ],
    displayOrder: 3,
    active: true,
  },
];
